services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: kurumachi_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d kurumachi_db']
      interval: 5s
      timeout: 5s
      retries: 5

  studio:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./firmware/web:/app
    command: npx prisma studio
    ports:
      - '5555:5555'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./firmware/web/.env

  web:
    build:
      context: ./firmware/web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./firmware/web:/app
      - /app/node_modules
      - /app/.next
      - /app/public/kurumachi # Ігноруємо важкі файли для Turbopack
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./firmware/web/.env.docker

volumes:
  postgres_data:
